Q1. What is the relationship between polynomial functions and kernel functions in machine learning
algorithms?

Ans.
In machine learning, the kernel function is used to transform the input data into a higher dimensional space. This is done by calculating the kernel function between each pair of data points. The resulting higher dimensional space is often more linearly separable than the original space, which can improve the performance of the machine learning algorithm.

Q2. How can we implement an SVM with a polynomial kernel in Python using Scikit-learn?

Ans.

To implement an SVM with a polynomial kernel in Python using Scikit-learn, we can use the SVC class. The SVC class has a parameter called kernel that can be set to polynomial. The polynomial kernel takes two parameters: degree and gamma. The degree parameter specifies the degree of the polynomial kernel. The gamma parameter specifies the kernel coefficient.

eg - 
import numpy as np
from sklearn.svm import SVC

#Create the data
X = np.array([[1, 2], [3, 4], [5, 6]])
y = np.array([0, 1, 1])

#Create the SVM classifier
clf = SVC(kernel='polynomial', degree=2, gamma=1)

#Train the classifier
clf.fit(X, y)

#Make predictions
predictions = clf.predict(X)

#Print the predictions
print(predictions)

Q3. How does increasing the value of epsilon affect the number of support vectors in SVR?

Ans.

In SVR, the epsilon parameter specifies the amount of error that is allowed for the predictions. When the value of epsilon is increased, the SVR algorithm will allow for more error in the predictions. This will result in a smaller number of support vectors being used.

Q4. How does the choice of kernel function, C parameter, epsilon parameter, and gamma parameter
affect the performance of Support Vector Regression (SVR)? Can you explain how each parameter works
and provide examples of when you might want to increase or decrease its value?

Ans.
he choice of kernel function, C parameter, epsilon parameter, and gamma parameter all affect the performance of SVR.

The kernel function determines how the data is transformed into a higher dimensional space. The C parameter controls the amount of regularization that is applied to the model. The epsilon parameter specifies the amount of error that is allowed for the predictions. The gamma parameter controls the smoothness of the decision boundary.

Here are some examples of when we might want to increase or decrease the value of each parameter:

1. Kernel function: If the data is not linearly separable, then you might want to use a kernel function that can transform the data into a higher dimensional space where it is linearly separable. For example, you might want to use a polynomial kernel with a high degree.

2. C parameter: If you want to reduce the risk of overfitting, then you might want to increase the value of the C parameter. This will make the model more complex and less likely to overfit the data.

3. Epsilon parameter: If you want to allow for more error in the predictions, then you might want to increase the value of the epsilon parameter. This will result in a smaller number of support vectors being used and a simpler decision boundary.

4. Gamma parameter: If you want to make the decision boundary smoother, then you might want to decrease the value of the gamma parameter. This will make the model less sensitive to noise in the data.


Q5. Assignment:
. Import the necessary libraries and load the dataset

. Split the dataset into training and testing set.

. Preprocess the data using any technique of your choice (e.g. scaling, normalization)

. Create an instance of the SVC classifier and train it on the training data

. hse the trained classifier to predict the labels of the testing datW

. Evaluate the performance of the classifier using any metric of your choice (e.g. accuracy,
precision, recall, F1-scoreK

. Tune the hyperparameters of the SVC classifier using GridSearchCV or RandomiMedSearchCV to
improve its performanc_

. Train the tuned classifier on the entire dataseg

. Save the trained classifier to a file for future use.

In [277]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import seaborn as sns

In [278]:
from sklearn.datasets import load_iris

In [279]:
dataset = load_iris()

In [280]:
df = pd.DataFrame(dataset.data , columns = dataset.feature_names)

In [281]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [282]:
df['Target'] = dataset.target

In [283]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   Target  
0       0  
1       0  
2       0  
3       0  
4       0

In [284]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [285]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [286]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [287]:
from sklearn.svm import SVC
svc = SVC()
svc.fit(X_train, y_train)


SVC()

In [288]:
y_pred = svc.predict(X_test)

In [289]:
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [290]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
score = r2_score(y_test,y_pred)
print(score)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

1.0
1.0
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [291]:
params = {
    'C':[1,2,3,4,5],
    'gamma':[1,0.1,0.01,0.001],
    'kernel':['rbf','poly','linear']
}

In [292]:
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(svc,param_grid = params , cv = 5, verbose = 3)

In [293]:
grid.fit(X_train,y_train)

Fitting 5 folds for each of 60 candidates, totalling 300 fits
[CV 1/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.958 total time=   0.0s
[CV 2/5] END ..........C=1, gamma=1, kernel=rbf;, score=1.000 total time=   0.0s
[CV 3/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.792 total time=   0.0s
[CV 4/5] END ..........C=1, gamma=1, kernel=rbf;, score=1.000 total time=   0.0s
[CV 5/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.917 total time=   0.0s
[CV 1/5] END .........C=1, gamma=1, kernel=poly;, score=0.958 total time=   0.0s
[CV 2/5] END .........C=1, gamma=1, kernel=poly;, score=0.917 total time=   0.0s
[CV 3/5] END .........C=1, gamma=1, kernel=poly;, score=0.875 total time=   0.0s
[CV 4/5] END .........C=1, gamma=1, kernel=poly;, score=0.958 total time=   0.0s
[CV 5/5] END .........C=1, gamma=1, kernel=poly;, score=0.958 total time=   0.0s
[CV 1/5] END .......C=1, gamma=1, kernel=linear;, score=0.958 total time=   0.0s
[CV 2/5] END .......C=1, gamma=1, kernel=linear

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1, 2, 3, 4, 5], 'gamma': [1, 0.1, 0.01, 0.001],
                         'kernel': ['rbf', 'poly', 'linear']},
             verbose=3)

In [294]:
grid.best_params_

{'C': 2, 'gamma': 1, 'kernel': 'linear'}

In [296]:
import pickle
with open('svc.pkl', 'wb') as file:
    pickle.dump(svc, file)